name: "Setup Node.js and Dependencies"
description: "Setup Node.js environment, pnpm, cache, and install dependencies"

runs:
  using: "composite"
  steps:
    - uses: jdx/mise-action@9e7f7633ff6f6d6048a9418a68d48f288f50eb14 # v4.2.3
    - run: pnpm install --frozen-lockfile
      shell: bash
